// Generated by CoffeeScript 1.9.3
(function() {
  var $, countdown, countdownTimer, currentCountdown, done, genNumbers, go, lpad, numbers, rand, updateCountdown;

  $ = document.querySelector.bind(document);

  rand = function(n) {
    return Math.floor(Math.random() * n);
  };

  currentCountdown = 0;

  countdownTimer = null;

  updateCountdown = function() {
    currentCountdown--;
    $('#countdown').textContent = currentCountdown;
    if (currentCountdown === 0) {
      return done();
    }
  };

  countdown = function(n) {
    currentCountdown = n;
    $('#countdown').textContent = currentCountdown;
    return countdownTimer = setInterval(updateCountdown, 1000);
  };

  numbers = [];

  lpad = function(str, n) {
    str = '' + str;
    while (str.length < n) {
      str = ' ' + str;
    }
    return str;
  };

  done = function() {
    var actual, answer, sum, text;
    clearInterval(countdownTimer);
    countdownTimer = null;
    sum = numbers.reduce(function(a, b) {
      return a + b;
    });
    if ($('#mode').value === 'avg') {
      actual = sum / numbers.length;
    } else {
      actual = sum;
    }
    text = (answer = $('#answer').value) ? "Actual:" + (lpad(actual, 4)) + ", Yours:" + (lpad(answer, 4)) + ", Difference: " + (Math.abs(actual - answer)) : "Too slow! " + actual;
    return $('#results').textContent = text + "\n" + $('#results').textContent;
  };

  genNumbers = function(count, sum) {
    var i, j, len, n, n2, ret, splits;
    splits = (function() {
      var j, ref, results;
      results = [];
      for (j = 1, ref = count - 1; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--) {
        results.push(Math.random());
      }
      return results;
    })();
    splits.push(1);
    splits.unshift(0);
    splits.sort(function(a, b) {
      return a - b;
    });
    ret = [];
    for (i = j = 0, len = splits.length; j < len; i = ++j) {
      n = splits[i];
      n2 = splits[i + 1];
      if (n2) {
        ret.push(Math.round((n2 - n) * sum));
      }
    }
    return ret;
  };

  go = function() {
    var total;
    countdown(5);
    total = Math.round(Math.random() * 1000);
    console.log("total", total);
    numbers = genNumbers(10, total);
    $('#numbers').textContent = numbers.join('\n');
    $('#answer').value = "";
    return $('#answer').focus();
  };

  $('#ready').addEventListener('click', go);

  $('#answer').addEventListener('keyup', function(e) {
    if (e.which === 13) {
      if (countdownTimer) {
        return done();
      } else {
        return go();
      }
    }
  });

}).call(this);
